socials:
  discord: "https://discord.gg/example"
  forums: "https://example.com/forums"
  vote1: "https://example.com/vote1"
  vote2: "https://example.com/vote2"
  vote3: "https://example.com/vote3"
  vote4: "https://example.com/vote4"