name: Socials
version: '${project.version}'
main: dev.michaelh.socials.Socials
authors: [ MichaelHayden ]
website: michael-h.dev

commands:
  discord:
    description: "Get the Discord invite link."
    usage: "/discord"
  forums:
    description: "Get the forums link."
    aliases: [ forum ]
    usage: "/forums"
  vote:
    description: "Get the vote links."
    usage: "/vote"